version: '3'
services:
  zookeeper:
    container_name: zookeeper
    image: quay.io/debezium/zookeeper:2.1
    networks:
      - ui-network
  kafka:
    container_name: kafka
    image: debezium/kafka
    ports:
      - "9092:9092"
    depends_on:
      - zookeeper
    environment:
      - ZOOKEEPER_CONNECT=zookeeper:2181
      - KAFKA_LOG_RETENTION_HOURS=2
      - KAFKA_LOG_RETENTION_CHECK_INTERVAL_MS=600000
      - KAFKA_BATCH_SIZE=150000
      - KAFKA_LINGER_MS=100
      - KAFKA_COMPRESSION_TYPE=lz4
      - KAFKA_ACKS=1
      - KAFKA_NUM_PARTITIONS=5
    networks:
      - ui-network
  db-pg:
    container_name: db-pg
    image: postgres:14
    ports:
      - "15432:5432"
    environment:
      POSTGRES_USER:
      POSTGRES_PASSWORD:
      POSTGRES_INITDB_ARGS: "--data-checksums"
    volumes:
      - ./pg_hba.conf:/etc/postgresql/14/main/pg_hba.conf
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - ui-network
  connect:
    container_name: connect
    image: debezium/connect
    build: .
    ports:
      - "8083:8083"
      - "1976:1976"
    depends_on:
      - kafka
      - db-pg
    environment:
      - BOOTSTRAP_SERVERS=kafka:9092
      - GROUP_ID=1
      - CONFIG_STORAGE_TOPIC=my_connect_configs
      - OFFSET_STORAGE_TOPIC=my_connect_offsets
      - STATUS_STORAGE_TOPIC=my_connect_statuses
      - ENABLE_DEBEZIUM_KC_REST_EXTENSION=true
      - ENABLE_DEBEZIUM_SCRIPTING=true
      - CONNECT_REST_EXTENSION_CLASSES=io.debezium.kcrestextension.DebeziumConnectRestExtension
      - KAFKA_HEAP_OPTS=-Xms256M -Xmx6G
    networks:
      - ui-network
  kafka-ui:
    container_name: kafka-ui
    image: provectuslabs/kafka-ui:v0.7.1
    ports:
      - "18083:8080"
    environment:
      - DYNAMIC_CONFIG_ENABLED=true
      - KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS=kafka:9092
      - KAFKA_CLUSTERS_0_NAME=local-app
      - KAFKA_CLUSTERS_0_KAFKACONNECT_0_NAME=first
      - KAFKA_CLUSTERS_0_KAFKACONNECT_0_ADDRESS=http://connect:8083
      # - AUTH_TYPE="LOGIN_FORM"
      # - SPRING_SECURITY_USER_NAME=admin
      # - SPRING_SECURITY_USER_PASSWORD=TechSU-1@
    depends_on:
      - kafka
      - connect
    networks:
      - ui-network
networks:
  ui-network:
    external: false